### ISSUE TITLE
Domain extraction issue

### ISSUE THREAD

**Issue by ghost** [sr-26/email-inspector#2]
On [L26](https://github.com/sr-26/email-inspector/blob/master/lib/validator.js#L26) in validator.js the domain part is extracted as the second token of the email string being split at the `@ `character boundary. 

Taking sections 3.2 and 3.4.1 of [RFC5322](https://www.rfc-editor.org/rfc/rfc5322) into consideration, the assumption that a valid email address can contain only one `@` character is not entirely correct. Technically, this is also a valid email address `"foo@bar"@example.com`

With that in mind, the safer approach to extract the domain part would be something like:

```
tokens = email.split('@')
domain = tokens.length > 1 ? tokens[tokens.length - 1] : undefined
```

**Comment by sr-26** [comment]
Hi @lszmit-nm
Thanks for catching that! We've updated the code to handle emails like "foo@bar"@example.com.

Appreciate your input!
